server: 
  port: 8001

spring:
  application:  
    name: project-backend-spring
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5342/bad_core
    username: baduser
    password: 5wNi@%99UA*acq5u
  jpa: 
    database: postgresql
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        format_sql: true
        user_sql_comments: true 
    